@startuml
left to right direction
title Registrace uživatele
skinparam packageStyle rect
actor :Nakladatel/vydavatel:
actor :Pracovník akvizice:
actor :Správce systému:

rectangle  {
	  :Nakladatel/vydavatel: --> (UC01-01 Stažení smlouvy)
	  :Pracovník akvizice: -left-> (UC01-02 Registrace nakladatele/vydavatele)
	  :Pracovník akvizice: -left-> (UC01-03 Pozastavení platnosti smlouvy s nakladatelem/vydavatelem)
	  :Pracovník akvizice: -left-> (UC01-04 Detail účtu nakladatele/vydavatele)
}
@endum