@startuml
left to right direction
title Registrace ISBN
skinparam packageStyle rect

actor :Systém:
actor :Nakladatel/vydavatel:
actor :Pracovník agentury ISBN:

rectangle  {

	   :Systém: -left-> (UC02-01 Načtení nově registrovaných ISBN)
	   :Nakladatel/vydavatel: --> (UC02-02 Prohledávání registrovaných ISBN)
}

:Pracovník agentury ISBN: ---> (Agentura ISBN: kontrola žádostí registace ISBN)
:Nakladatel/vydavatel: ---> (www.nkp.cz: Zadání žádosti o registraci ISBN)	

@enduml