@startuml
left to right direction
title Registrace ISBN
skinparam packageStyle rect
actor :Nakladatel/vydavatel:
actor :Pracovník agentury ISBN:

rectangle  {
	   :Nakladatel/vydavatel: --> (UC02-01 Zadání žádosti o registraci ISBN)
	   :Nakladatel/vydavatel: --> (UC02-02 Prohledávání registrovaných ISBN)
}
@enduml