@startuml
left to right direction
title Katalogizace e-publikace

skinparam packageStyle rect

actor :Nakladatel/vydavatel: as nakl
actor :Pracovník akvizice: as akv
actor :Pracovník katalogizace: as kat
actor :Systém: as sys

rectangle  {
	   :kat: -left-> (UC04-01 Zadání bibliografických metadat)
	   :sys: -left-> (UC04-02 Export do systému Kramerius)
	   :nakl: --> (UC04-03 Oprava souboru)
	   :nakl: --> (UC04-04 Stáhnutí souboru)
	   :kat: -left-> (UC04-05 Odebrání přístupu k e-publikaci)
	   :kat: -left-> (UC04-06 Odmítnutí e-publikace)
}
@enduml